require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ClimaBuilder' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Permissions Location
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"


  target 'ClimaBuilderTests' do
    inherit! :complete
  end

end
